# Custom MSVC toolchain for Conan/CMake
# This file enforces debug info format and linker optimizations for all configurations

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(MSVC)
    # Debug configuration: use /Z7, remove /Zi, add linker optimizations
    set(CMAKE_CXX_FLAGS_DEBUG "/MDd /Z7 /Ob0 /Od /RTC1" CACHE STRING "" FORCE)
    set(CMAKE_C_FLAGS_DEBUG "/MDd /Z7 /Ob0 /Od /RTC1" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)
    set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)
    set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)
    set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "Old" CACHE STRING "" FORCE)
    set(CMAKE_CXX_FLAGS_DEBUG_INIT "" CACHE STRING "" FORCE)
    set(CMAKE_C_FLAGS_DEBUG_INIT "" CACHE STRING "" FORCE)

    # Release configuration
    set(CMAKE_CXX_FLAGS_RELEASE "/MD /O2 /GL /DNDEBUG" CACHE STRING "" FORCE)
    set(CMAKE_C_FLAGS_RELEASE "/MD /O2 /GL /DNDEBUG" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)
    set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)
    set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)

    # RelWithDebInfo configuration: use Release flags
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/MD /O2 /GL /DNDEBUG" CACHE STRING "" FORCE)
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "/MD /O2 /GL /DNDEBUG" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)
    set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)
    set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "/OPT:REF /OPT:ICF" CACHE STRING "" FORCE)
endif()
